### PR TITLE
oom and lmk fixes

### PR DESCRIPTION
**Pull request by Realex-fire**
1) Sync missing changes with linux 3.15 for oom and lmk.
2) Add trace kill events with linux upstream for lmk.
3) Sync other bugfix changes with linux upstream and dorimanx LG G2 kernel.
This should fix the remaining FCs. I'm testing it 2 days, FCs do not appear (this is record for my phone).

Thank you for attention.

### CODE REVIEW

**Comment by gsstudios** [comment]
Thanks, will test shortly

**Comment by gsstudios** [comment]
Its running fine on my phone. I will need to test for a few days before keeping this change.

**Comment by gsstudios** [comment]
Unfortunately, FCs still occur

**Comment by Realex-fire** [comment]
I do watch fewer FCs for 3 days. 
Ps: I test it using BFQ and Linaro 4.9
PPs: Today FCs there again...
PPPs: Try to update bootbin in initramfs for last cm11

**Comment by Realex-fire** [comment]
You can also try to disable "CONFIG_ANDROID_LOW_MEMORY_KILLER_AUTODETECT_OOM_ADJ_VALUES" in the config.

**Comment by gsstudios** [comment]
I haven't had a FC for a while now, I'll see when FCs happen again

**Comment by Realex-fire** [comment]
Ok, then I will be testing with disabled "CONFIG_ANDROID_LOW_MEMORY_KILLER_AUTODETECT_OOM_ADJ_VALUES" till Monday.

**Pull request merged**
