### PR TITLE
Sync forgotten change with linux mainstream

### PR DESCRIPTION
**Pull request by Realex-fire**

### CODE REVIEW

**Comment by gsstudios** [comment]
Somehow I'm stuck at dori kernel logo. Recovery mode seems to be not working.

**Comment by Realex-fire** [comment]
very strange ... I'll check it
it could spoil only the Internet...

ps: I need some time to check it.

**Comment by gsstudios** [comment]
I think I'm just experiencing partition corruption.

**Comment by Realex-fire** [comment]
Indeed, kernel will not load ... it needs some work.

**Comment by chhapil** [comment]
Do you face this partition corruption issue frequently? I guess some piece kernel related to fs in not properly merged, I normally see dirty partition after 5 6 days of use. Or it may be due to fsync I'm not sure of that.

**Comment by gsstudios** [comment]
I rarely get corruption issues. Right now I need to reflash ROM.

**Comment by gsstudios** [comment]
I'll leave this merged for now until I can get my device working properly again.

**Comment by Realex-fire** [comment]
It is very strange, interesting that caused such behavior.

**Comment by gsstudios** [comment]
Now I will revert until everything is all good.

**Pull request merged**
